//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedaEntitiesDb : DbContext
    {
        public MedaEntitiesDb()
            : base("name=MedaEntitiesDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblHeadofficeCroatia> tblHeadofficeCroatias { get; set; }
        public virtual DbSet<tblHeadofficeSlovenia> tblHeadofficeSlovenias { get; set; }
        public virtual DbSet<tblInstitutionCroatia> tblInstitutionCroatias { get; set; }
        public virtual DbSet<tblInstitutionSlovenia> tblInstitutionSlovenias { get; set; }
        public virtual DbSet<tblInstitutionSubtype> tblInstitutionSubtypes { get; set; }
        public virtual DbSet<tblInstitutionType> tblInstitutionTypes { get; set; }
        public virtual DbSet<vwInstitution> vwInstitutions { get; set; }
        public virtual DbSet<vwInstitutionCroatia> vwInstitutionCroatias { get; set; }
        public virtual DbSet<vwInstitutionSlovenia> vwInstitutionSlovenias { get; set; }
        public virtual DbSet<tblHeadofficeSerbia> tblHeadofficeSerbias { get; set; }
        public virtual DbSet<tblInstitutionSerbia> tblInstitutionSerbias { get; set; }
        public virtual DbSet<vwInstitutionSerbia> vwInstitutionSerbias { get; set; }
        public virtual DbSet<tblBrand> tblBrands { get; set; }
        public virtual DbSet<tblPacking> tblPackings { get; set; }
        public virtual DbSet<tblPrimaryImport> tblPrimaryImports { get; set; }
        public virtual DbSet<tblPrimaryPacking> tblPrimaryPackings { get; set; }
        public virtual DbSet<tblPrimaryWholesale> tblPrimaryWholesales { get; set; }
        public virtual DbSet<tblWholesale> tblWholesales { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<vwPrimaryMissingPacking> vwPrimaryMissingPackings { get; set; }
        public virtual DbSet<vwPrimaryMissingWholesale> vwPrimaryMissingWholesales { get; set; }
    }
}
