//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int packing_id { get; set; }
        public string Packing { get; set; }
        public int brand_id { get; set; }
        public string Brand { get; set; }
        public string THERAP_AREA { get; set; }
        public string TargetStatus { get; set; }
    }
}
