//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstitutionSerbia
    {
        public int insID { get; set; }
        public string insName { get; set; }
        public string insAddress { get; set; }
        public int ctyID { get; set; }
        public int isbID { get; set; }
        public int hdoID { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblHeadofficeSerbia tblHeadofficeSerbia { get; set; }
        public virtual tblInstitutionSubtype tblInstitutionSubtype { get; set; }
    }
}
