//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrimaryWholesale
    {
        public int piwID { get; set; }
        public int whsID { get; set; }
        public string pimWholesale { get; set; }
        public string pimCountry { get; set; }
    
        public virtual tblWholesale tblWholesale { get; set; }
    }
}
