//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPacking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPacking()
        {
            this.tblPrimaryPackings = new HashSet<tblPrimaryPacking>();
        }
    
        public int pacID { get; set; }
        public string pacName { get; set; }
        public int braID { get; set; }
        public string pacTherapArea { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPrimaryPacking> tblPrimaryPackings { get; set; }
    }
}
