//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrimaryImport
    {
        public int pimID { get; set; }
        public string pimPacking { get; set; }
        public int monID { get; set; }
        public int yeaID { get; set; }
        public decimal pimQuantity { get; set; }
        public decimal pimGrossSales { get; set; }
        public decimal pimNetSales { get; set; }
        public string pimWholesales { get; set; }
        public string pimCountry { get; set; }
    }
}
