//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrimaryPacking
    {
        public int ppaID { get; set; }
        public int pacID { get; set; }
        public string pimPacking { get; set; }
    
        public virtual tblPacking tblPacking { get; set; }
    }
}
