//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedaSlovenija
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInstitutionCroatia
    {
        public int insID { get; set; }
        public string insName { get; set; }
        public string ctyName { get; set; }
        public string insAddress { get; set; }
        public string isbName { get; set; }
        public string itpName { get; set; }
        public string hdoName { get; set; }
        public int ctyID { get; set; }
        public int isbID { get; set; }
        public int itpID { get; set; }
        public int hdoID { get; set; }
    }
}
